CREATE SEQUENCE sede_id_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE SEDES (
        ID_SEDE BIGINT NOT NULL DEFAULT nextval('sede_id_seq') PRIMARY KEY,
        NOMBRE_CORTO VARCHAR(120) NOT NULL,
        NOMBRE_LARGO VARCHAR(400) NOT NULL,
        ESTADO VARCHAR(1) NOT NULL DEFAULT '1'
);

ALTER SEQUENCE sede_id_seq OWNED BY SEDES.ID_SEDE;